-- AFFOS RLS (PRD-017). service_role ghi (bypass); authenticated đọc; anon chặn. Không secret.
alter table affiliate_networks enable row level security;
drop policy if exists affiliate_networks_read_auth on affiliate_networks;
create policy affiliate_networks_read_auth on affiliate_networks for select to authenticated using (true);
alter table merchants enable row level security;
drop policy if exists merchants_read_auth on merchants;
create policy merchants_read_auth on merchants for select to authenticated using (true);
alter table products enable row level security;
drop policy if exists products_read_auth on products;
create policy products_read_auth on products for select to authenticated using (true);
alter table offers enable row level security;
drop policy if exists offers_read_auth on offers;
create policy offers_read_auth on offers for select to authenticated using (true);
alter table channels enable row level security;
drop policy if exists channels_read_auth on channels;
create policy channels_read_auth on channels for select to authenticated using (true);
alter table content enable row level security;
drop policy if exists content_read_auth on content;
create policy content_read_auth on content for select to authenticated using (true);
alter table campaigns enable row level security;
drop policy if exists campaigns_read_auth on campaigns;
create policy campaigns_read_auth on campaigns for select to authenticated using (true);
alter table tracking_links enable row level security;
drop policy if exists tracking_links_read_auth on tracking_links;
create policy tracking_links_read_auth on tracking_links for select to authenticated using (true);
alter table click_events enable row level security;
drop policy if exists click_events_read_auth on click_events;
create policy click_events_read_auth on click_events for select to authenticated using (true);
alter table conversion_events enable row level security;
drop policy if exists conversion_events_read_auth on conversion_events;
create policy conversion_events_read_auth on conversion_events for select to authenticated using (true);
alter table commissions enable row level security;
drop policy if exists commissions_read_auth on commissions;
create policy commissions_read_auth on commissions for select to authenticated using (true);
alter table expenses enable row level security;
drop policy if exists expenses_read_auth on expenses;
create policy expenses_read_auth on expenses for select to authenticated using (true);
alter table revenue enable row level security;
drop policy if exists revenue_read_auth on revenue;
create policy revenue_read_auth on revenue for select to authenticated using (true);
alter table customers enable row level security;
drop policy if exists customers_read_auth on customers;
create policy customers_read_auth on customers for select to authenticated using (true);
alter table experiments enable row level security;
drop policy if exists experiments_read_auth on experiments;
create policy experiments_read_auth on experiments for select to authenticated using (true);
alter table opportunities enable row level security;
drop policy if exists opportunities_read_auth on opportunities;
create policy opportunities_read_auth on opportunities for select to authenticated using (true);
alter table agent_registry enable row level security;
drop policy if exists agent_registry_read_auth on agent_registry;
create policy agent_registry_read_auth on agent_registry for select to authenticated using (true);
alter table skill_registry enable row level security;
drop policy if exists skill_registry_read_auth on skill_registry;
create policy skill_registry_read_auth on skill_registry for select to authenticated using (true);
alter table agent_runs enable row level security;
drop policy if exists agent_runs_read_auth on agent_runs;
create policy agent_runs_read_auth on agent_runs for select to authenticated using (true);
alter table audit_logs enable row level security;
drop policy if exists audit_logs_read_auth on audit_logs;
create policy audit_logs_read_auth on audit_logs for select to authenticated using (true);
alter table system_events enable row level security;
drop policy if exists system_events_read_auth on system_events;
create policy system_events_read_auth on system_events for select to authenticated using (true);
